"""add style_session_id to makeup_sessions

Revision ID: 828ff791ee4b
Revises: 
Create Date: 2025-12-25 10:13:23.954576+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828ff791ee4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('makeup_history', sa.Column('style_session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'makeup_history', 'user_style_sessions', ['style_session_id'], ['id'])
    op.add_column('makeup_sessions', sa.Column('style_session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'makeup_sessions', 'user_style_sessions', ['style_session_id'], ['id'])
    op.drop_column('makeup_sessions', 'accessories_image_url')
    op.drop_column('makeup_sessions', 'outfit_image_url')
    op.add_column('scheduled_events', sa.Column('style_session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scheduled_events', 'user_style_sessions', ['style_session_id'], ['id'])
    op.drop_column('scheduled_events', 'outfit_image_url')
    op.drop_index('ix_user_profiles_user_id', table_name='user_profiles')
    op.create_unique_constraint(None, 'user_profiles', ['user_id'])
    op.create_foreign_key(None, 'user_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.create_index('ix_user_profiles_user_id', 'user_profiles', ['user_id'], unique=False)
    op.add_column('scheduled_events', sa.Column('outfit_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'scheduled_events', type_='foreignkey')
    op.drop_column('scheduled_events', 'style_session_id')
    op.add_column('makeup_sessions', sa.Column('outfit_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('makeup_sessions', sa.Column('accessories_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'makeup_sessions', type_='foreignkey')
    op.drop_column('makeup_sessions', 'style_session_id')
    op.drop_constraint(None, 'makeup_history', type_='foreignkey')
    op.drop_column('makeup_history', 'style_session_id')
    # ### end Alembic commands ###
