"""Add new columns to vanity_products

Revision ID: 09a26d362309
Revises: 828ff791ee4b
Create Date: 2025-12-26 09:57:13.614887+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '09a26d362309'
down_revision = '828ff791ee4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_database', 'category',
               existing_type=postgresql.ENUM('FOUNDATION', 'CONCEALER', 'POWDER', 'BLUSH', 'BRONZER', 'HIGHLIGHTER', 'EYESHADOW', 'EYELINER', 'KAJAL', 'MASCARA', 'EYEBROW', 'LIPSTICK', 'LIP_GLOSS', 'LIP_LINER', 'PRIMER', 'SETTING_SPRAY', 'TOOLS', 'OTHER', name='productcategory'),
               nullable=True)
    op.alter_column('product_database', 'brand',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('vanity_products', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('vanity_products', sa.Column('product_source', sa.String(length=50), nullable=True))
    op.add_column('vanity_products', sa.Column('enrichment_confidence', sa.Float(), nullable=True))
    op.add_column('vanity_products', sa.Column('meta_data', sa.JSON(), nullable=True))
    op.add_column('vanity_products', sa.Column('skin_safety_rating', sa.Float(), nullable=True))
    op.add_column('vanity_products', sa.Column('allergy_conflicts', sa.JSON(), nullable=True))
    op.alter_column('vanity_products', 'category',
               existing_type=postgresql.ENUM('FOUNDATION', 'CONCEALER', 'POWDER', 'BLUSH', 'BRONZER', 'HIGHLIGHTER', 'EYESHADOW', 'EYELINER', 'KAJAL', 'MASCARA', 'EYEBROW', 'LIPSTICK', 'LIP_GLOSS', 'LIP_LINER', 'PRIMER', 'SETTING_SPRAY', 'TOOLS', 'OTHER', name='productcategory'),
               nullable=True)
    op.alter_column('vanity_products', 'brand',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('vanity_products_user_id_fkey', 'vanity_products', type_='foreignkey')
    op.create_foreign_key(None, 'vanity_products', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vanity_products', type_='foreignkey')
    op.create_foreign_key('vanity_products_user_id_fkey', 'vanity_products', 'users', ['user_id'], ['id'])
    op.alter_column('vanity_products', 'brand',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('vanity_products', 'category',
               existing_type=postgresql.ENUM('FOUNDATION', 'CONCEALER', 'POWDER', 'BLUSH', 'BRONZER', 'HIGHLIGHTER', 'EYESHADOW', 'EYELINER', 'KAJAL', 'MASCARA', 'EYEBROW', 'LIPSTICK', 'LIP_GLOSS', 'LIP_LINER', 'PRIMER', 'SETTING_SPRAY', 'TOOLS', 'OTHER', name='productcategory'),
               nullable=False)
    op.drop_column('vanity_products', 'allergy_conflicts')
    op.drop_column('vanity_products', 'skin_safety_rating')
    op.drop_column('vanity_products', 'meta_data')
    op.drop_column('vanity_products', 'enrichment_confidence')
    op.drop_column('vanity_products', 'product_source')
    op.drop_column('vanity_products', 'description')
    op.alter_column('product_database', 'brand',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('product_database', 'category',
               existing_type=postgresql.ENUM('FOUNDATION', 'CONCEALER', 'POWDER', 'BLUSH', 'BRONZER', 'HIGHLIGHTER', 'EYESHADOW', 'EYELINER', 'KAJAL', 'MASCARA', 'EYEBROW', 'LIPSTICK', 'LIP_GLOSS', 'LIP_LINER', 'PRIMER', 'SETTING_SPRAY', 'TOOLS', 'OTHER', name='productcategory'),
               nullable=False)
    # ### end Alembic commands ###
